# Generated by Django 3.2.12 on 2023-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
