# Generated by Django 3.2.12 on 2023-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Rating', models.CharField(max_length=5)),
                ('Review', models.CharField(max_length=330)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
