# Generated by Django 3.2.12 on 2023-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(max_length=3),
        ),
    ]
