# Generated by Django 3.2.12 on 2023-01-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Review',
            field=models.CharField(max_length=200),
        ),
    ]
