# Generated by Django 3.2.12 on 2023-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_order_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
