# Generated by Django 3.2.12 on 2023-03-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_order_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=45)),
                ('Lastname', models.CharField(max_length=45)),
                ('Adress', models.CharField(max_length=45)),
                ('Phoneno', models.CharField(max_length=12)),
                ('AmountPaid', models.DecimalField(decimal_places=3, max_digits=5)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order')),
            ],
        ),
    ]
