# Generated by Django 3.2.25 on 2025-04-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20250414_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='AmountPaid',
        ),
    ]
