# Generated by Django 3.2.25 on 2025-04-17 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_checkout_amountpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Phoneno',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
