# Generated by Django 3.2.12 on 2022-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superuser'), (2, 'staff'), (3, 'student'), (4, 'tutor')], null=True),
        ),
    ]
